<a href="https://colab.research.google.com/github/joaopedro-r/Ia-projetos/blob/main/Credito_jogos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install mlrose

In [ ]:
import mlrose

# Organizar Dados

In [ ]:
lista_precos = []

for linhas in open('/content/drive/MyDrive/Colab Notebooks/league_of_legends_RP.txt'):
  diamantes, reais = linhas.split(',')
  lista_precos.append((int(diamantes), float(reais)))

In [ ]:
lista_precos

[(650, 13.65),
 (1380, 27.25),
 (2800, 54.5),
 (5000, 95.5),
 (7200, 136.25),
 (15000, 272.5)]

In [ ]:
atual = 160
skin = 9000

# Função fitness

In [ ]:
def fitness_function(lista_fit):
  diamantes_max = skin
  soma_diamantes = atual
  soma_reais = 0
  for a in range(len(lista_precos)):
    if lista_fit[a] > 0:
      soma_diamantes += lista_precos[a][0]*lista_fit[a]
      soma_reais += lista_precos[a][1]*lista_fit[a]

  if soma_diamantes < diamantes_max:
    soma_reais = 99999999

  return soma_reais

In [ ]:
fitness = mlrose.CustomFitness(fitness_function)
problema = mlrose.DiscreteOpt(length=len(lista_precos), fitness_fn=fitness, maximize=False, max_val=10)


# algoritimo genetico

In [ ]:
melhor_solucao, melhor_custo = mlrose.genetic_alg(problema, pop_size=1000, mutation_prob=0.3)
melhor_solucao, melhor_custo

(array([9, 0, 1, 1, 0, 0]), 272.85)

# Hill climb 

In [ ]:
melhor_solucao, melhor_custo = mlrose.hill_climb(problema)
melhor_solucao, melhor_custo


(array([3, 0, 0, 0, 0, 0]), 40.95)

# simulating annealing

In [ ]:
melhor_solucao, melhor_custo = mlrose.simulated_annealing(problema)
melhor_solucao, melhor_custo

/usr/local/lib/python3.7/dist-packages/mlrose/algorithms.py:311: RuntimeWarning: overflow encountered in exp
  prob = np.exp(delta_e/temp)


(array([0, 1, 5, 0, 1, 0]), 436.0)

# Imprimir solucao

In [ ]:
def imprimir_solucao(lista_fit):
  diamantes_max = skin
  soma_diamantes = atual
  soma_reais = 0
  print('\n')
  print('-='*50)
  print(f'Voce tem {atual} RPs')
  print('\n')
  print(f'para comprar essa skin, ou ter o valor de {diamantes_max} RPs voce deve comprar os de:')

  for a in range(len(lista_precos)):
    if lista_fit[a] > 0:
      soma_diamantes += lista_precos[a][0] * lista_fit[a]
      soma_reais += lista_precos[a][1] * lista_fit[a]
      if lista_fit[a] == 1:
        print(f'{lista_fit[a]}- {lista_precos[a][0]} RPs -> R${lista_precos[a][1]}')
      else:
        print(f'{lista_fit[a]}- {lista_precos[a][0]} RPs -> R${lista_precos[a][1]} | R${round(lista_precos[a][1]*lista_fit[a], 2)}')
  if soma_diamantes < diamantes_max:
    soma_reais = 99999999
  print(f'\nVoce terá no final {soma_diamantes} RPs')
  print(f'Custando R${round(soma_reais, 2)}')

In [ ]:
imprimir_solucao(melhor_solucao)



-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Voce tem 160 RPs


para comprar essa skin, ou ter o valor de 9000 RPs voce deve comprar os de:
9- 650 RPs -> R$13.65 | R$122.85
1- 2800 RPs -> R$54.5
1- 5000 RPs -> R$95.5

Voce terá no final 13810 RPs
Custando R$272.85
